package com.squarepegsystems;

import org.joda.beans.Bean;
import org.joda.beans.MetaBean;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;


import java.util.Map;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
public class Author implements Bean {


    @PropertyDefinition(validate = "notEmpty")
    private String lastName;

    @PropertyDefinition(validate = "notEmpty")
    private String firstName;
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code Author}.
     * @return the meta-bean, not null
     */
    public static Author.Meta meta() {
        return Author.Meta.INSTANCE;
    }

    static {
        MetaBean.register(Author.Meta.INSTANCE);
    }

    @Override
    public Author.Meta metaBean() {
        return Author.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the lastName.
     * @return the value of the property, not empty
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the lastName.
     * @param lastName  the new value of the property, not empty
     */
    public void setLastName(String lastName) {
        JodaBeanUtils.notEmpty(lastName, "lastName");
        this.lastName = lastName;
    }

    /**
     * Gets the the {@code lastName} property.
     * @return the property, not null
     */
    public final Property<String> lastName() {
        return metaBean().lastName().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the firstName.
     * @return the value of the property, not empty
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the firstName.
     * @param firstName  the new value of the property, not empty
     */
    public void setFirstName(String firstName) {
        JodaBeanUtils.notEmpty(firstName, "firstName");
        this.firstName = firstName;
    }

    /**
     * Gets the the {@code firstName} property.
     * @return the property, not null
     */
    public final Property<String> firstName() {
        return metaBean().firstName().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public Author clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            Author other = (Author) obj;
            return JodaBeanUtils.equal(getLastName(), other.getLastName()) &&
                    JodaBeanUtils.equal(getFirstName(), other.getFirstName());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getLastName());
        hash = hash * 31 + JodaBeanUtils.hashCode(getFirstName());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(96);
        buf.append("Author{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("lastName").append('=').append(JodaBeanUtils.toString(getLastName())).append(',').append(' ');
        buf.append("firstName").append('=').append(JodaBeanUtils.toString(getFirstName())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code Author}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code lastName} property.
         */
        private final MetaProperty<String> lastName = DirectMetaProperty.ofReadWrite(
                this, "lastName", Author.class, String.class);
        /**
         * The meta-property for the {@code firstName} property.
         */
        private final MetaProperty<String> firstName = DirectMetaProperty.ofReadWrite(
                this, "firstName", Author.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "lastName",
                "firstName");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1459599807:  // lastName
                    return lastName;
                case 132835675:  // firstName
                    return firstName;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends Author> builder() {
            return new DirectBeanBuilder<>(new Author());
        }

        @Override
        public Class<? extends Author> beanType() {
            return Author.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code lastName} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> lastName() {
            return lastName;
        }

        /**
         * The meta-property for the {@code firstName} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> firstName() {
            return firstName;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1459599807:  // lastName
                    return ((Author) bean).getLastName();
                case 132835675:  // firstName
                    return ((Author) bean).getFirstName();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1459599807:  // lastName
                    ((Author) bean).setLastName((String) newValue);
                    return;
                case 132835675:  // firstName
                    ((Author) bean).setFirstName((String) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

        @Override
        protected void validate(Bean bean) {
            JodaBeanUtils.notEmpty(((Author) bean).lastName, "lastName");
            JodaBeanUtils.notEmpty(((Author) bean).firstName, "firstName");
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
